apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-app
  template:
    metadata:
      labels:
        app: blog-app
    spec:
      containers:
      - name: blog-app
        image: ved104/blog-go-app:1
        ports:
        - containerPort: 8080
        env:
        - name: KAFKA_BROKERS
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: KAFKA_BROKERS
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: blog-secrets
              key: db_url
        readinessProbe:
          exec:
            command: ["sh", "-c", "nc -z kafka 9092 && nc -z postgres 5432"]
          initialDelaySeconds: 20
          periodSeconds: 5


--- 

apiVersion: v1
kind: Service
metadata:
  name: blog-app-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: blog-app
  ports:
  - port: 8080
    targetPort: 8080

